before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: e3biCTf9Grk8fIL83RcDvVP+WY/cuQDzQFbko3G5/IhWYcKIYmnW80Yw+zWZhUToVIKJP/CYAhuyHyvE6dOs1gtrHXXoTHgpzGPcucUsTu/ahoE9zftZXvghUfteFmApxhK57X3linA2SyKzZbsWm1Ru9KyvJ/wZW+o4eVkfLCIoCaVcTYM4NFZWiHosfV6uy8xrBbGu5DUE/Fjq7/SvWnb5Qh5ZVy3QIae9Er+EADdL97MRB0aDGZrZhKMDTk63VBeIoPimA+fT4R3Woe2JTzu+5nQCbZbVwbBXlJ8wNx8cyfZcD8aKoUNCKBVHzZ3ULNCuB1BYf09aqmMRkNv7N/f5etW3xj3iOwp6pnKYhJiaCtlalnp45EU1eRHOUcq3W5n5fChSxLaxQ+rNSCodNIzYU2FXWJ9TNj4BX81Y7JAGB6wk7b3ghz/DQbAmmMNWu+Z6qZFxPZzsmVgp6PnIqw5/uaGUmanK+Rt9EzpFmzysr9gs9tQGUA6+D5J71ehfft8j3EuF/B7DdMBlig4vNDZD7LY89EahJyyGwdpZzTOIFMu4yZFrtjXSABFBHEqy2hdlMToNJ/SovbJszPe2CMvPkzvKV5OQB0saRn4eqJk99RvmcsoJ781eVDS97RglXLtX5kQV2VoOOfdpTBw43aSl18P27f8g1cbZObaqjs4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
